# Soccer dataset

In [2]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path

# =====================================================================
# Database path
# =====================================================================
# Your database is here:
#   C:\Users\Madsl\Dropbox\DTU\Kand\3.Semester\MBML\Project_MBML\data\database.sqlite

db_path = Path(r"C:\Users\Madsl\Dropbox\DTU\Kand\3.Semester\MBML\Project_MBML\data\database.sqlite")

# Safety check to prevent SQLite from creating an empty database
if (not db_path.exists()) or db_path.stat().st_size == 0:
    raise FileNotFoundError(
        f"Database not found at: {db_path.resolve()}\n"
        "SQLite may create an empty file if the path is wrong."
    )

# Create the SQLite connection
conn = sqlite3.connect(str(db_path))
print(f"Successfully connected to {db_path} via sqlite3!")

# Query the master table for all user table names
tables_query = """
    SELECT name 
    FROM sqlite_master 
    WHERE type='table';
"""
tables_df = pd.read_sql(tables_query, conn)

print("Tables in the SQLite Database:")
display(tables_df)

countries_leagues_query = """
    SELECT Country.name as CountryName, 
           League.name as LeagueName 
    FROM League
    JOIN Country ON Country.id = League.country_id;
"""

leagues_df = pd.read_sql(countries_leagues_query, conn)
display(leagues_df)

Successfully connected to C:\Users\Madsl\Dropbox\DTU\Kand\3.Semester\MBML\Project_MBML\data\database.sqlite via sqlite3!
Tables in the SQLite Database:

                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

    CountryName                LeagueName
0       Belgium    Belgium Jupiler League
1       England    England Premier League
2        France            France Ligue 1
3       Germany     Germany 1. Bundesliga
4         Italy             Italy Serie A
5   Netherlands    Netherlands Eredivisie
6        Poland        Poland Ekstraklasa
7      Portugal  Portugal Liga ZON Sagres
8      Scotland   Scotland Premier League
9         Spain           Spain LIGA BBVA
10  Switzerland  Switzerland Super League

In [5]:
# Extract only the English Premier League matches
# We join the Match table with the League and Team tables to get readable names
epl_query = """
    SELECT 
        M.season, 
        M.stage,
        M.date,
        HT.team_long_name AS home_team,
        AT.team_long_name AS away_team,
        M.home_team_goal, 
        M.away_team_goal
    FROM Match M
    JOIN League L ON M.league_id = L.id
    JOIN Team HT ON HT.team_api_id = M.home_team_api_id
    JOIN Team AT ON AT.team_api_id = M.away_team_api_id
    WHERE L.name = 'England Premier League'
    ORDER BY M.date DESC;
"""

epl_matches = pd.read_sql(epl_query, conn)

print(f"Total Premier League matches found: {len(epl_matches)}")
display(epl_matches.head(10))

#save the dataframe to a csv file
epl_matches.to_csv("epl_matches.csv", index=False)
print("Saved EPL matches to 'epl_matches.csv'")

Total Premier League matches found: 3040

,season,stage,date,home_team,away_team,home_team_goal,away_team_goal
0,2015/2016,38,2016-05-17 00:00:00,Manchester United,Bournemouth,3,1
1,2015/2016,38,2016-05-15 00:00:00,Arsenal,Aston Villa,4,0
2,2015/2016,38,2016-05-15 00:00:00,Chelsea,Leicester City,1,1
3,2015/2016,38,2016-05-15 00:00:00,Everton,Norwich City,3,0
4,2015/2016,38,2016-05-15 00:00:00,Newcastle United,Tottenham Hotspur,5,1
5,2015/2016,38,2016-05-15 00:00:00,Southampton,Crystal Palace,4,1
6,2015/2016,38,2016-05-15 00:00:00,Stoke City,West Ham United,2,1
7,2015/2016,38,2016-05-15 00:00:00,Swansea City,Manchester City,1,1
8,2015/2016,38,2016-05-15 00:00:00,Watford,Sunderland,2,2
9,2015/2016,38,2016-05-15 00:00:00,West Bromwich Albion,Liverpool,1,1

Saved EPL matches to 'epl_matches.csv'

In [6]:
#load csv and display
epl_matches_loaded = pd.read_csv("epl_matches.csv")
display(epl_matches_loaded.head(10))

,season,stage,date,home_team,away_team,home_team_goal,away_team_goal
0,2015/2016,38,2016-05-17 00:00:00,Manchester United,Bournemouth,3,1
1,2015/2016,38,2016-05-15 00:00:00,Arsenal,Aston Villa,4,0
2,2015/2016,38,2016-05-15 00:00:00,Chelsea,Leicester City,1,1
3,2015/2016,38,2016-05-15 00:00:00,Everton,Norwich City,3,0
4,2015/2016,38,2016-05-15 00:00:00,Newcastle United,Tottenham Hotspur,5,1
5,2015/2016,38,2016-05-15 00:00:00,Southampton,Crystal Palace,4,1
6,2015/2016,38,2016-05-15 00:00:00,Stoke City,West Ham United,2,1
7,2015/2016,38,2016-05-15 00:00:00,Swansea City,Manchester City,1,1
8,2015/2016,38,2016-05-15 00:00:00,Watford,Sunderland,2,2
9,2015/2016,38,2016-05-15 00:00:00,West Bromwich Albion,Liverpool,1,1